// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-demo-calculator/calculator/calc/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/calc/add",
				Handler: addHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/calc/mul",
				Handler: mulHandler(serverCtx),
			},
		},
	)
}
