// Code generated by goctl. DO NOT EDIT.
package types

type AddReq struct {
	A int64 `json:"a"`
	B int64 `json:"b"`
}

type AddReply struct {
	Res int64 `json:"res"`
}

type MulReq struct {
	A int64 `json:"a"`
	B int64 `json:"b"`
}

type MulReply struct {
	Res int64 `json:"res"`
}
