// Code generated by goctl. DO NOT EDIT.
// Source: adder.proto

package server

import (
	"context"

	"go-zero-demo-calculator/calculator/adder/rpc/internal/logic"
	"go-zero-demo-calculator/calculator/adder/rpc/internal/svc"
	"go-zero-demo-calculator/calculator/adder/rpc/types/adder"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	adder.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) Add(ctx context.Context, in *adder.AddRequest) (*adder.AddResponse, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
