// Code generated by goctl. DO NOT EDIT.
// Source: adder.proto

package adderclient

import (
	"context"

	"go-zero-demo-calculator/calculator/adder/rpc/types/adder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRequest  = adder.AddRequest
	AddResponse = adder.AddResponse

	Adder interface {
		Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	}

	defaultAdder struct {
		cli zrpc.Client
	}
)

func NewAdder(cli zrpc.Client) Adder {
	return &defaultAdder{
		cli: cli,
	}
}

func (m *defaultAdder) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	client := adder.NewAdderClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
